version: "3.7"

services:
  arrebol-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - arrebol-net
    ports:
      - "5432:5432"
    volumes:
      - arrebol:/var/lib/postgresql/data
  dba:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "emanueljbm@lsd.ufcg.edu.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    networks:
      - arrebol-net
    ports:
      - 15432:80

#  arrebol:
#    image: ufcglsd/arrebol:golang
#    env_file:
#      - ./.env
#    networks:
#      - arrebol
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 10s
#    ports:
#      - "8080:8080"

volumes:
  arrebol: {}

networks:
  arrebol-net:
