version: "3.7"

services:
  arrebol-db:
    image: postgres
    environment:
      POSTGRES_USER: "arrebol-admin"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "arrebol-db"
    networks:
      - arrebol-net
    ports:
      - "5432:5432"
    volumes:
      - arrebol-db:/var/lib/postgresql/data
  dba:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "emanueljbm@lsd.ufcg.edu.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    networks:
      - arrebol-net
    ports:
      - 15432:80

  arrebol:
    image: emanueljoivo/arrebol:0.0.4
    env_file:
      - ../.env
    networks:
      - arrebol-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "5000:5000"

volumes:
  arrebol-db: {}

networks:
  arrebol-net:
    driver: overlay
